language: minimal
dist: focal
git:
  depth: 5

matrix:
  include:
  - env:
      - task=shellcheck
    before_install:
      - bash --version
      - shellcheck --version
    script:
      - bash -n setup.sh
      - shellcheck -e SC1117 -s bash setup.sh

  - env:
      - task=ubuntu1604
    dist: xenial
    script:
      - sudo ./setup.sh

  - env:
      - task=ubuntu1804
    dist: bionic
    script:
      - sudo ./setup.sh

  - env:
      - task=ubuntu2004
    dist: focal
    script:
      - sudo ./setup.sh
