language: minimal
dist: xenial
git:
  depth: 5

matrix:
  include:
  - env:
      - task=shellcheck
    before_install:
      - bash --version
      - shellcheck --version
    script:
      - bash -n setup.sh
      - shellcheck -e SC1117 -s bash setup.sh

  - env:
      - task=ubuntu1604
    services:
    - docker
    script:
    - docker run -i --rm -v "${PWD}:/ci-temp/" ubuntu:16.04 bash -c "/ci-temp/setup.sh"

  - env:
      - task=ubuntu1804
    services:
    - docker
    script:
    - docker run -i --rm -v "${PWD}:/ci-temp/" ubuntu:18.04 bash -c "/ci-temp/setup.sh"

  - env:
      - task=ubuntu2004
    services:
    - docker
    script:
    - docker run -i --rm -v "${PWD}:/ci-temp/" ubuntu:20.04 bash -c "/ci-temp/setup.sh"
