language: generic
dist: trusty
sudo: required
git:
  depth: 5
addons:
  apt:
    packages:
      - cabal-install
      - ghc
env:
  - PATH="$PATH:~/.cabal/bin/"
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
before_install:
  - bash --version
install:
  - cabal update && cabal install ShellCheck && shellcheck --version
script:
  - bash -n setup.sh
  - shellcheck -s bash setup.sh
